blank_issues_enabled: false
contact_links:
  - name: "\U00002753 General Question"
    url: https://github.com/jeffltc01/appQSCMESv2/discussions
    about: Ask a question or start a discussion (if Discussions is enabled)
